### ISSUE TITLE
Perfil del propietario/usuario y edición

### ISSUE THREAD

**Issue by Arezlon** [Arezlon/Inmobiliaria-Moviles-Grupo-4#4]
Vista con datos del usuario y un enlace a otra vista que permita editarlos.

**Comment by Eourist** [comment]
Falta validar campos en el formulario de edición (no permitir campos vacíos, DNI de 8 dígitos, teléfono de 10 a 15 dígitos, email con '@' y '.')

**Comment by Eourist** [comment]
Sacar el focus automático de un campo a otro en el formulario de edición (eso de que cuando tocas "siguiente" te salta al próximo input) porque no todos los campos son obligatorios.
