### ISSUE TITLE
Listado de contratos + detalles + pagos

### ISSUE THREAD

**Issue by Arezlon** [Arezlon/Inmobiliaria-Moviles-Grupo-4#6]
Mostrar un listado de contratos con un enlace a vista de detalles. La vista de detalles muestra datos del contrato y del inquilino, y un enlace que nos lleve a un listado de pagos.

El fragment del listado se llama desde el menú navegable/contratos y muestra todos los inmuebles del usuario con contratos vigentes en el momento. Para llenar el ListView se puede reutilizar el ListaInmueblesAdapter y la vista list_item_inmueble.xml que se usaron para la lista de inmuebles.
El fragment de detalles se puede llamar desde el listado de contratos/detalle y muestra los datos del contrato y del inquilino.
El fragment de pagos también usa un ListView (como el listado de inmuebles con contratos) que muestra todos los pagos de ese contrato.

**Comment by Eourist** [comment]
Para llenar el ListView creo que se puede reutilizar el ListaInmueblesAdapter y la vista list_item_inmueble.xml
